spring:
  datasource.url: jdbc:h2:~/solteq-demo-java-db
  jpa.hibernate.ddl-auto: update
  jpa.properties.hibernate:
    show_sql: false
    use_sql_comments: true
    format_sql: true

logging:
  level:
    org:
      hibernate:
        type: info
    com:
      slupicki: debug
    net:
      sf:
        jasperreports: debug
