spring:
  datasource.url: jdbc:h2:~/solteq-demo-db
  jpa.hibernate.ddl-auto: update
  jpa.properties.hibernate:
    show_sql: true
    use_sql_comments: true
    format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace